### PR TITLE
Bump prometheus-operator version

### PR DESCRIPTION
**Pull request by fpetkovski**
Updates PO version to 0.52.1

### CODE REVIEW

**Comment by simonpasquier** [comment]
hmm it looks like the master -> main change hits again...

**Comment by simonpasquier** [comment]
we would need to change this line?

https://github.com/prometheus-operator/website/blob/a06bf4e3d849ea3d23db864b252b59ee44e2618c/synchronize.sh#L8

**Comment by fpetkovski** [comment]
Yes, this seems to have done the trick. I added it as a new commit to make sure the change stays separate.

**Review by simonpasquier — APPROVED** [review]
lgtm

**Pull request merged**
